"""add sites and update bookings

Revision ID: 065ba595809f
Revises: 56ae5585cd25
Create Date: 2026-07-22 19:18:44.807395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '065ba595809f'
down_revision: Union[str, Sequence[str], None] = '56ae5585cd25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_name', sa.String(length=150), nullable=False),
    sa.Column('site_type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_site_name'), 'sites', ['site_name'], unique=False)
    op.add_column('bookings', sa.Column('loading_site_id', sa.UUID(), nullable=False))
    op.add_column('bookings', sa.Column('unloading_site_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('bookings_unloading_location_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_loading_location_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'sites', ['loading_site_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'sites', ['unloading_site_id'], ['id'])
    op.drop_column('bookings', 'unloading_location_id')
    op.drop_column('bookings', 'loading_location_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('loading_location_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('unloading_location_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_loading_location_id_fkey'), 'bookings', 'locations', ['loading_location_id'], ['id'])
    op.create_foreign_key(op.f('bookings_unloading_location_id_fkey'), 'bookings', 'locations', ['unloading_location_id'], ['id'])
    op.drop_column('bookings', 'unloading_site_id')
    op.drop_column('bookings', 'loading_site_id')
    op.drop_index(op.f('ix_sites_site_name'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
