"""create bookings table

Revision ID: 56ae5585cd25
Revises: 029a5583da07
Create Date: 2026-07-22 16:17:45.928634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ae5585cd25'
down_revision: Union[str, Sequence[str], None] = '029a5583da07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_number', sa.String(length=30), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('loading_location_id', sa.UUID(), nullable=False),
    sa.Column('unloading_location_id', sa.UUID(), nullable=False),
    sa.Column('bill_to', sa.String(length=150), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('freight_type', sa.String(length=50), nullable=True),
    sa.Column('customer_freight', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('customer_advance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('customer_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('broker_freight', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('broker_advance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('broker_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('bill_submission_status', sa.String(length=50), nullable=True),
    sa.Column('payment_received_date', sa.Date(), nullable=True),
    sa.Column('payment_received_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['loading_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['unloading_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_number'), 'bookings', ['booking_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_booking_number'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
