"""create customers table

Revision ID: b2e9168cc53b
Revises: 
Create Date: 2026-07-21 18:18:38.566897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e9168cc53b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_code', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_code')
    )
    op.create_index(op.f('ix_customers_customer_name'), 'customers', ['customer_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_customer_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
